// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaqdjyheurykelzumtjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhcWRqeWhldXJ5a2VsenVtdGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDg1NTgsImV4cCI6MjA2MDI4NDU1OH0.9BVm-kmzk6131P6muSZIjostMjpFCqSNDp3klpUihic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);